name: Publish EC 1.2-b Specs
on:
  # Triggers the workflow on push or pull request events but only for the v1.1beta_helm_pkg_update_lber_ay branch
  #push:
  #  branches: [ 1.2-b ]
  #pull_request:
  #  branches: [ 1.2-b ]
  #  types: [opened, synchronize]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    environment: v1
    env:
      GITHUB_AGT_TAG: "ghcr.io/ec-release/agt:1.2-b"
      #depreacted
      #GITHUB_API_TAG: "ghcr.io/ec-release/api:1.2-b"
      GITHUB_API_TAG: "ghcr.io/ec-release/sdr:1.2-b"
      GITHUB_SDC_TAG: "ghcr.io/ec-release/sdc:1.2-b"
      GITHUB_REGISTRY: "https://ghcr.io"
      GITHUB_USR: "ayasuda-ge"
      
      #deprecated
      #DOCKER_ATH_TAG: "enterpriseconnect/oauth:v1.2beta"
      DOCKER_ATH_TAG: "enterpriseconnect/sdc:1.2-b"
      #deprecated
      #DOCKER_API_TAG: "enterpriseconnect/api:v1.2beta"
      DOCKER_API_TAG: "enterpriseconnect/sdr:1.2-b"
      #deprecated
      #GITHUB_ATH_TAG: "ghcr.io/ec-release/oauth:v1.2beta"
      #deprecated
      #GITHUB_OLD_API_TAG: "ghcr.io/ec-release/api:v1.2beta"
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
        with: 
          ref: 1.2-b
      - name: Container Runtime Building
        env:
          EC_REV_V1: 1.2-b
        run: |
          cd ./spec/sdc && docker build -t $GITHUB_SDC_TAG . && cd -
          cd ./spec/agt && docker build -t $GITHUB_AGT_TAG . && cd -
          cd ./spec/api && docker build -t $GITHUB_API_TAG . && cd -
   
      - name: Container Test
        env:
          AGENT_REV: temp
          EC_PPS: ${{secrets.EC_PPS_2_DECRYPT_213}}
        run: |
          docker run $GITHUB_AGT_TAG -ver
          #runtime test resplaced by int test
          #docker run $GITHUB_API_TAG -ver
      - name: Container Images Deployment
        #if: github.event_name == 'push'
        env:
          REGISTRY_TKN_GITHUB: ${{secrets.REGISTRY_TKN_GITHUB}}
          DOCKER_USERNAME: apoloyasudadocker
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}        
        run: |
          echo $REGISTRY_TKN_GITHUB | docker login $GITHUB_REGISTRY -u $GITHUB_USR --password-stdin
          docker push $GITHUB_AGT_TAG
          docker push $GITHUB_SDC_TAG
          docker push $GITHUB_API_TAG
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker tag $GITHUB_SDC_TAG $DOCKER_ATH_TAG
          docker tag $GITHUB_SDC_TAG $GITHUB_ATH_TAG
          docker push $DOCKER_ATH_TAG
          docker push $GITHUB_ATH_TAG
          docker tag $GITHUB_API_TAG $DOCKER_API_TAG
          docker tag $GITHUB_API_TAG $GITHUB_OLD_API_TAG
          docker push $DOCKER_API_TAG
          docker push $GITHUB_OLD_API_TAG
          
          
