name: Publish EC v1.2-b Specs
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    environment: v1
    env:
      DOCKER_HUB_AGT_TAG: "enterpriseconnect/agt:1.2-b"
      #deprecated
      #DOCKER_HUB_API_TAG: "enterpriseconnect/api:v1.2beta"
      DOCKER_HUB_API_TAG: "enterpriseconnect/sdr:v1.2beta"
      #deprecated
      #DOCKER_HUB_OAUTH_TAG: "enterpriseconnect/oauth:v1.2beta"
      DOCKER_HUB_OAUTH_TAG: "enterpriseconnect/sdc:v1.2beta"
      GITHUB_AGT_TAG: "ghcr.io/ec-release/agt:1.2-b"
      #deprecated
      #GITHUB_API_TAG: "ghcr.io/ec-release/api:1.2-b"
      GITHUB_API_TAG: "ghcr.io/ec-release/sdr:1.2-b"
      #deprecated
      #GITHUB_OAUTH_TAG: "ghcr.io/ec-release/oauth:1.2-b"
      GITHUB_OAUTH_TAG: "ghcr.io/ec-release/sdc:1.2-b"
      GITHUB_REGISTRY: "https://ghcr.io"
      GITHUB_USR: "ayasuda-ge"
    
    steps:
      - uses: actions/checkout@v2

      - name: Container Runtime Building
        env:
          EC_REV_V1: v1.2-b
        run: |
          cd ./spec/agt && docker build -t $DOCKER_HUB_AGT_TAG . && cd -
          cd ./spec/api && docker build -t $DOCKER_HUB_API_TAG . && cd -
          cd ./spec/oauth && docker build -t $DOCKER_HUB_OAUTH_TAG . && cd -
       
      - name: Container Test
        env:
          AGENT_REV: v1.hokkaido.213
          #EC_PPS: ${{secrets.EC_PPS_2_DECRYPT_213}}
        run: |
          chmod +x ./scripts/docker-deployment-sim.sh
          ./scripts/docker-deployment-sim.sh
      - name: Container Images Deployment
        #if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true        
        if: github.event_name == 'push'       
        env:
          DOCKER_USERNAME: apoloyasudadocker
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
          REGISTRY_TKN_GITHUB: ${{secrets.REGISTRY_TKN_GITHUB}}
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker push $DOCKER_HUB_AGT_TAG
          docker push $DOCKER_HUB_API_TAG
          docker push $DOCKER_HUB_OAUTH_TAG
          docker tag $DOCKER_HUB_AGT_TAG $GITHUB_AGT_TAG
          docker tag $DOCKER_HUB_API_TAG $GITHUB_API_TAG
          docker tag $DOCKER_HUB_OAUTH_TAG $GITHUB_OAUTH_TAG
          echo $REGISTRY_TKN_GITHUB | docker login $GITHUB_REGISTRY -u $GITHUB_USR --password-stdin
          docker push $GITHUB_AGT_TAG
          docker push $GITHUB_API_TAG
          docker push $GITHUB_OAUTH_TAG
